
const wordData = {
    "arena": {
        "word": "arena/areny",
        "translation": "арена",
        "image": "https://cdn1.e-polish.eu/4e8b0fa7/o31d7spx8mnppvsh/arena.jpeg",
        "sentence": "Klaun występuje na cyrkowej arenie.",
        "p1": "им.п. - arena / areny",
        "p2": "род.п. — areny / aren",
        "p3": "дат.п. — arenie / arenom",
        "p4": "вин.п. — arenę / areny",
        "p5": "твор.п. — areną / arenami",
        "p6": "предл.п. — arenie / arenach",
        "p7": "зват.п. — areno / areny",
        "audio": "./audio/04B/arena.mp3"
    },
    "bieg na krótkim dystansie": {
        "word": "bieg na krótkim dystansie",
        "translation": "бег на короткое расстояние",
        "image": "https://cdn1.e-polish.eu/709e371d/ha8doqswfky9kffz/bieg_na_krotkim_dystansie.jpg",
        "sentence": "Zawsze zwyciężam w biegu na krótkim dystansie. ",
        "p1": "фраза ",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "audio": "./audio/04B/bieg na krótkim dystansie.mp3"
    },
    "boisko": {
        "word": "boisko",
        "translation": "спортивная площадка",
        "image": "https://cdn1.e-polish.eu/4e8b0fa7/q6m4hutprcvxzrvq/boisko.jpeg",
        "sentence": "Na boisku rozegrano mecz.",
        "p1": "существительное, средний род",
        "p2": "им.п. - boisko / boiska",
        "p3": "род.п. — boiska / boisk",
        "p4": "дат.п. — boisku / boiskom",
        "p5": "вин.п. — boisko / boiska",
        "p6": "твор.п. — boiskiem / boiskami",
        "p7": "предл.п. — boisku / boiskach",
        "p8": "зват.п. — boisko / boiska",
        "audio": "./audio/04B/boisko.mp3"
    },
    "bramka": {
        "word": "bramka",
        "translation": "футбольные ворота",
        "image": "https://cdn1.e-polish.eu/709e371d/1pgypchr4ihkqhui/bramka.jpg",
        "sentence": "Piłkarz nie trafił piłką do bramki. ",
        "p1": "существительное, женский род",
        "p2": "им.п. - bramka / bramki",
        "p3": "род.п. — bramki / bramek",
        "p4": "дат.п. — bramce / bramkom",
        "p5": "вин.п. — bramkę / bramki",
        "p6": "твор.п. — bramką / bramkami",
        "p7": "предл.п. — bramce / bramkach",
        "p8": "зват.п. — bramko / bramki",
        "audio": "./audio/04B/bramka.mp3"
    },
    "bramkarz": {
        "word": "bramkarz ",
        "translation": "вратарь",
        "image": "https://cdn1.e-polish.eu/4e8b0fa7/ow36h174o01cvn5i/bramkarz.jpeg",
        "sentence": "Bramkarz tej drużyny jest dobry, nie wpuścił żadnego gola. ",
        "p1": "существительное, мужской род",
        "p2": "им.п. - bramkarz / bramkarze",
        "p3": "род.п. — bramkarza / bramkarzy",
        "p4": "дат.п. — bramkarzowi / bramkarzom",
        "p5": "вин.п. — bramkarza / bramkarzy",
        "p6": "твор.п. — bramkarzem / bramkarzami",
        "p7": "предл.п. — bramkarzu / bramkarzach",
        "p8": "зват.п. — bramkarzu / bramkarze",
        "audio": "./audio/04B/bramkarz.mp3"
    },
    "cel": {
        "word": "cel",
        "translation": "мишень",
        "image": "https://cdn1.e-polish.eu/4e8b0fa7/1tzmhovrdwzgb4hg/cel.jpeg",
        "sentence": "Mój życiowy cel to zrobienie kariery.",
        "p1": "существительное, мужской род",
        "p2": "им.п. - cel / cele",
        "p3": "род.п. — celu / celów",
        "p4": "дат.п. — celowi / celom",
        "p5": "вин.п. — cel / cele",
        "p6": "твор.п. — celem / celami",
        "p7": "предл.п. — celu / celach",
        "p8": "зват.п. — celu / cele",
        "audio": "./audio/04B/cel.mp3"
    },
     "ceremoniał": {
        "word": "ceremoniał",
        "translation": "церемония",
        "image": "https://cdn1.e-polish.eu/4e8b0fa7/o2pmhmmacs1lw88x/ceremonia_1.jpeg",
        "sentence": "Ceremoniał zaślubin przebiega w Kośclele katolickim zawsze tak samo.",
        "p1": "существительное, мужской род",
        "p2": "им.п. - ceremoniał / ceremoniały",
        "p3": "род.п. — ceremoniału / ceremoniałów ",
        "p4": "дат.п. — ceremoniałowi / ceremoniałom ",
        "p5": "вин.п. — ceremoniał / ceremoniały",
        "p6": "твор.п. — ceremoniałem / ceremoniałami ",
        "p7": "предл.п. — ceremoniale / ceremoniałach ",
        "p8": "зват.п. — ceremoniale / ceremoniały ",
        "audio": "./audio/04B/ceremonial.mp3"
    },
     "chód": {
        "word": "chód",
        "translation": "походка",
        "image": "https://cdn1.e-polish.eu/709e371d/aztq3z8j7vey1k6c/chod.jpg",
        "sentence": "Masz taki dziwny chód, boli cię noga?",
        "p1": "существительное, мужской род",
        "p2": "им.п. - chód / singulare tantum ",
        "p3": "род.п. — chodu ",
        "p4": "дат.п. — chodowi",
        "p5": "вин.п. — chód",
        "p6": "твор.п. — chodem",
        "p7": "предл.п. — chodzie",
        "p8": "зват.п. — chodzie",
        "audio": "./audio/04B/chód.mp3"
    },
    "dołek": {
        "word": "dołek",
        "translation": "ямка",
        "image": "https://cdn1.e-polish.eu/4e8b0fa7/0bx7jdncutmattam/dolek.jpeg",
        "sentence": "Chłopiec wykopał dołek w piasku.",
        "p1": "существительное, мужской род",
        "p2": "им.п. - dołek / dołki ",
        "p3": "род.п. — dołka / dołków",
        "p4": "дат.п. — dołkowi / dołkom",
        "p5": "вин.п. — dołek / dołki ",
        "p6": "твор.п. — dołkiem / dołkami",
        "p7": "предл.п. — dołku / dołkach",
        "p8": "зват.п. — dołku / dołki",
        "audio": "./audio/04B/dołek.mp3"
    },
    "drużyna": {
        "word": "drużyna",
        "translation": "команда",
        "image": "https://cdn1.e-polish.eu/709e371d/aq6zemj238j2e7zv/druzyna.jpg",
        "sentence": "Drużyna z Polski wygrała mecz.",
        "p1": "существительное, женский род",
        "p2": "им.п. - drużyna / drużyny ",
        "p3": "род.п. — drużyny / drużyn ",
        "p4": "дат.п. — drużynie / drużynom ",
        "p5": "вин.п. — drużynę / drużyny",
        "p6": "твор.п. — drużyną / drużynami",
        "p7": "предл.п. — drużynie / drużynach ",
        "p8": "зват.п. — drużyno / drużyny",
        "audio": "./audio/04B/drużyna.mp3"
    },
    "feudalny": {
        "word": "feudalny",
        "translation": "феодальный",
        "image": "",
        "sentence": "W średniowieczu panował ustrój feudalny.",
        "p1": "прилагательное",
        "p2": "им.п. - feudalny / feudalni,feudalne ",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/feudalny.mp3"
    },
    "igrzyska olimpijskie": {
        "word": "igrzyska olimpijskie",
        "translation": "олимпийские игры",
        "image": "https://cdn1.e-polish.eu/709e371d/neryajj0w2b7pbt8/igrzyska_olimpijskie.png",
        "sentence": "Igrzyska olimpijskie w 2012 roku odbyły się w Londynie.",
        "p1": "фраза",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/igrzyska olimpijskie.mp3"
    },
     "kij": {
        "word": "kij",
        "translation": "олимпийские игры",
        "image": "https://cdn1.e-polish.eu/4e8b0fa7/8udc8h4l9na2huvv/kij.jpeg",
        "sentence": "Mężczyzna odpędzał psy kijem.",
        "p1": "существительное, мужской род",
        "p2": "им.п. - kij / kije",
        "p3": "род.п. — kija / kijów",
        "p4": "дат.п. — kijowi / kijom ",
        "p5": "вин.п. — kij / kije",
        "p6": "твор.п. — kijem / kijami",
        "p7": "предл.п. — kiju / kijach ",
        "p8": "зват.п. — kiju / kije",
        "audio": "./audio/04B/kij .mp3"
    },
    "kondycja fizyczna": {
        "word": "kondycja fizyczna ",
        "translation": "физическая кондиция",
        "image": "https://cdn1.e-polish.eu/709e371d/81lfw7as79icwote/kondycja_fizyczna.jpg",
        "sentence": "Mało ćwiczę, więc mam kiepską kondycję fizyczną. ",
        "p1": "фраза ",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/kondycja fizyczna.mp3"
    },
    "odbicie": {
        "word": "odbicie",
        "translation": "отображение",
        "image": "https://cdn1.e-polish.eu/4e8b0fa7/lzd7bdcu9snrgb2i/odbicie.jpeg",
        "sentence": "Codziennie rano przyglądam się swojemu odbiciu w lustrze.",
        "p1": "существительное, средний род",
        "p2": "им.п. - odbicie / odbicia ",
        "p3": "род.п. — odbicia / odbić",
        "p4": "дат.п. — odbiciu / odbiciom ",
        "p5": "вин.п. — odbicie / odbicia ",
        "p6": "твор.п. — odbiciem / odbiciami",
        "p7": "предл.п. — odbiciu / odbiciach",
        "p8": "зват.п. — odbicie / odbicia",
        "audio": "./audio/04B/odbicie.mp3"
    },
    "odbijać piłkę": {
        "word": "odbijać piłkę",
        "translation": "отбивать мяч",
        "image": "https://cdn1.e-polish.eu/709e371d/jnt6xyya7plj6bkn/odbijac_pilke.jpg",
        "sentence": "Dzieci odbijają piłkę do siebie. ",
        "p1": "фраза",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/odbijać piłkę.mp3"
    },
    "pole walki": {
        "word": "pole walki",
        "translation": "поле борьбы ",
        "image": "https://cdn1.e-polish.eu/709e371d/zycb3hbreyd5kt1f/pole_walki.jpg",
        "sentence": "Żołnierze wrogich armii starli się na polu walki. ",
        "p1": "фраза",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/pole walki.mp3"
    },
     "połowa": {
        "word": "połowa",
        "translation": "половина",
        "image": "https://cdn1.e-polish.eu/709e371d/ukgt27wbeye7i8ez/polowa.jpg",
        "sentence": "Zjedliśmy połowę ciasta.",
        "p1": "существительное, женский род",
        "p2": "им.п. - połowa / połowy ",
        "p3": "род.п. — połowy / połów",
        "p4": "дат.п. — połowie / połowom ",
        "p5": "вин.п. — połowę / połowy",
        "p6": "твор.п. — połową / połowami ",
        "p7": "предл.п. — połowie / połowach  ",
        "p8": "зват.п. — połowo / połowy ",
        "audio": "./audio/04B/polowa.mp3"
    },
    "prostokątny": {
        "word": "prostokątny",
        "translation": "прямоугольный",
        "image": "https://cdn1.e-polish.eu/709e371d/ig28zvcvo6c6ys0l/prostokatny.jpg",
        "sentence": "Usiedliśmy przy prostokątnym stole. ",
        "p1": "прилагательное",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/prostokątny.mp3"
    },
    "przebywać na świeżym": {
        "word": "przebywać na świeżym powietrzu ",
        "translation": "находиться на свежем воздухе ",
        "image": "https://cdn1.e-polish.eu/709e371d/hs7tj85jxxa13psl/na_swiezym_powietrzu.jpg",
        "sentence": "Musisz dużo przebywać na świeżym powietrzu, to dobre dla zdrowia.",
        "p1": "фраза ",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/przebywać na świeżym.mp3"
    },
     "przeciwnik": {
        "word": "przeciwnik",
        "translation": "противник",
        "image": "https://cdn1.e-polish.eu/709e371d/nzc64fy7l76pygaq/przeciwnik.jpg",
        "sentence": "Przeciwnikiem Dawida był Goliat.",
        "p1": "существительное, мужской род",
        "p2": "им.п. - przeciwnik / przeciwnicy ",
        "p3": "род.п. — przeciwnika / przeciwników",
        "p4": "дат.п. — przeciwnikowi / przeciwnikom ",
        "p5": "вин.п. — przeciwnika / przeciwników ",
        "p6": "твор.п. — przeciwnikiem / przeciwnikami",
        "p7": "предл.п. — przeciwniku / przeciwnikach ",
        "p8": "зват.п. — przeciwniku / przeciwnicy",
        "audio": "./audio/04B/przeciwnik.mp3"
    },
    "przewrócić": {
        "word": "przewrócić",
        "translation": "перевернуть",
        "image": "",
        "sentence": "Adaś przewrócił Krzysia.",
        "p1": "глагол, совершенного вида",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/przewrócić.mp3"
    },
    "regulaminowy czas gry": {
        "word": "regulaminowy czas gry",
        "translation": "установленное время игры",
        "image": "http://cdn1.e-polish.eu/709e371d/1x6j025udsv2sg5g/regulaminowy_czas_gry.jpg",
        "sentence": "Regulaminowy czas gry to 45 minut.",
        "p1": "фраза ",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/regulaminowy czas gry.mp3"
    },
    "rzut dyskiem": {
        "word": "rzut dyskiem",
        "translation": "метание диска",
        "image": "https://cdn1.e-polish.eu/709e371d/ffm1w22klnnhc8dg/rzut_dyskiem.png",
        "sentence": "Rzut dyskiem to dyscyplina olimpijska.",
        "p1": "фраза ",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/rzut dyskiem.mp3"
    },
     "siatka": {
        "word": "siatka",
        "translation": "сетка",
        "image": "https://cdn1.e-polish.eu/709e371d/379qzytydn37w1jf/siatka1.png",
        "sentence": "Ogród jest ogrodzony siatką. ",
        "p1": "существительное, женский род",
        "p2": "им.п. - siatka / siatki ",
        "p3": "род.п. — siatki / siatek",
        "p4": "дат.п. — siatce / siatkom ",
        "p5": "вин.п. — siatkę / siatki",
        "p6": "твор.п. — siatką / siatkami",
        "p7": "предл.п. — siatce / siatkach",
        "p8": "зват.п. — siatko / siatki ",
        "audio": "./audio/04B/siatka.mp3"
    },
    "skok w dal": {
        "word": "skok w dal",
        "translation": "прыжок вдаль",
        "image": "https://cdn1.e-polish.eu/709e371d/6iiplm3886dvp3b6/skok_w_dal.jpg",
        "sentence": "Skok w dal jest dyscypliną olimpijską.",
        "p1": "фраза ",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/skok w dal.mp3"
    },
    "snob": {
        "word": "snob",
        "translation": "сноб",
        "image": "",
        "sentence": "Piotr to snob, nosi tylko markowe ubrania i jada w drogich restauracjach. ",
        "p1": "существительное, мужской род",
        "p2": "им.п. - snob / snobi,snoby ",
        "p3": "род.п. — snoba / snobów",
        "p4": "дат.п. — snobowi / snobom",
        "p5": "вин.п. — snoba / snobów",
        "p6": "твор.п. — snobem / snobami",
        "p7": "предл.п. — snobie / snobach",
        "p8": "зват.п. — snobie / snobi,snoby",
        "audio": "./audio/04B/snob.mp3"
    },
    "starożytny": {
        "word": "starożytny",
        "translation": "древний ",
        "image": "https://cdn1.e-polish.eu/709e371d/1a6ca8nsbhlcwg5x/starozytny.jpg",
        "sentence": "Piramidy to starożytny zabytek.",
        "p1": "прилагательное",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/starozytny.mp3"
    },
     "stopa": {
        "word": "stopa",
        "translation": "стопа ",
        "image": "https://cdn1.e-polish.eu/709e371d/io0h2bivyuoay3vo/stopa.jpg",
        "sentence": "Ubierz skarpetki, to będzie ci ciepło w stopy. ",
        "p1": "существительное, женский род",
        "p2": "им.п. - stopa / stopy",
        "p3": "род.п. — stopy / stóp",
        "p4": "дат.п. — stopie / stopom",
        "p5": "вин.п. — stopę / stopy",
        "p6": "твор.п. — stopą / stopami ",
        "p7": "предл.п. — stopie / stopach ",
        "p8": "зват.п. — stopo! / stopy!",
        "audio": "./audio/04B/stopa.mp3"
    },
     "trawa": {
        "word": "trawa",
        "translation": "трава",
        "image": "https://cdn1.e-polish.eu/709e371d/mxamx4evay9bsahd/trawa.jpg",
        "sentence": "Na łące rośnie trawa. ",
        "p1": "существительное, женский род",
        "p2": "им.п. - trawa / trawy",
        "p3": "род.п. — trawy / traw",
        "p4": "дат.п. — trawie / trawom",
        "p5": "вин.п. — trawę / trawy ",
        "p6": "твор.п. — trawą / trawami",
        "p7": "предл.п. — trawie / trawach ",
        "p8": "зват.п. — trawo! / trawy!",
        "audio": "./audio/04B/trawa.mp3"
    },
    "umieścić": {
        "word": "umieścić",
        "translation": "поместить",
        "image": "https://cdn1.e-polish.eu/4e8b0fa7/9mh1jijo8o4u3v6y/umiescic.jpeg",
        "sentence": "Na czas podróży umieściłem kota w kojcu.",
        "p1": "глагол, совершенного вида",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/umieścić.mp3"
    },
    "w kształcie koła": {
        "word": "w kształcie koła",
        "translation": "в виде круга",
        "image": "https://cdn1.e-polish.eu/709e371d/121win9wfh78em25/w_ksztalcie_kola.jpg",
        "sentence": "Otwarto nowy basen w kształcie koła. ",
        "p1": "фраза",
        "p2": "",
        "p3": "",
        "p4": "",
        "p5": "",
        "p6": "",
        "p7": "",
        "p8": "",
        "audio": "./audio/04B/w kształcie koła.mp3"
    },
    "wypchnąć": {
        "word": "wypchnąć",
        "translation": "вытолкнуть",
        "image": "https://cdn1.e-polish.eu/709e371d/5gf7rjug7nyu72h5/wypchnac.jpg",
        "sentence": "1. Mężczyzna wypchnął swoją żonę przez okno.  2. Nauczyciel wypchnął dzieci z sali. ",
        "p1": "глагол, совершенного вида",
        "p2": "я - wypchnąłem / wypchnęłam ",
        "p3": "ты - wypchnąłeś / wypchnęłaś ",
        "p4": "он - wypchnął / ona,ono - wypchnęła,wypchnęło",
        "p5": "мы - wypchnęliśmy / wypchnęłyśmy",
        "p6": "вы - wypchnęliście / wypchnęłyście ",
        "p7": "они - wypchnęli / wypchnęły ",
        "p8": "",
        "audio": "./audio/04B/wypchnąć.mp3"
    },
    "wywodzić się": {
        "word": "wywodzić się",
        "translation": "походить ",
        "image": "https://cdn1.e-polish.eu/709e371d/78itqzg6zp333cwp/wywodzic_sie.jpg",
        "sentence": "Czy wiesz, z jakiego środowiska się wywodzisz?",
        "p1": "глагол, несовершенного вида",
        "p2": "я - wywodzę się",
        "p3": "ты - wywodzisz się",
        "p4": "он,ona,ono - wywodzi się",
        "p5": "мы - wywodzimy się ",
        "p6": "вы - wywodzicie się ",
        "p7": "они - wywodzą się",
        "p8": "",
        "audio": "./audio/04B/wywodzić się.mp3"
    },
     "wzrost": {
        "word": "wzrost",
        "translation": "рост",
        "image": "https://cdn1.e-polish.eu/709e371d/d2ocaflc4ckbdmni/wzrost.jpg",
        "sentence": "Mam 150 centymetrów wzrostu. W wyniku kryzysu mamy do czynienia z wzrostem cen. ",
        "p1": "существительное, мужской род",
        "p2": "им.п. - wzrost",
        "p3": "род.п. — wzrostu",
        "p4": "дат.п. — wzrostowi",
        "p5": "вин.п. — wzrost",
        "p6": "твор.п. — wzrostem",
        "p7": "предл.п. — wzroście",
        "p8": "зват.п. — wzroście",
        "audio": "./audio/04B/wzrost.mp3"
    },
     "zawodnik": {
        "word": "zawodnik",
        "translation": "спортсмен",
        "image": "https://cdn1.e-polish.eu/709e371d/q1zlpdi4oksuxany/zawodnik.jpg",
        "sentence": "Zawodnik drużyny Brazylii strzelił gola w meczu. ",
        "p1": "существительное, мужской род",
        "p2": "им.п. - zawodnik / zawodnicy",
        "p3": "род.п. — zawodnika / zawodników",
        "p4": "дат.п. — zawodnikowi / zawodnikom",
        "p5": "вин.п. — zawodnika / zawodników",
        "p6": "твор.п. — zawodnikiem / zawodnikami",
        "p7": "предл.п. — zawodniku / zawodnikach",
        "p8": "зват.п. — zawodniku / zawodnicy ",
        "audio": "./audio/04B/zawodnik.mp3"
    },
    "zwycięzca": {
        "word": "zwycięzca",
        "translation": "победитель",
        "image": "https://cdn1.e-polish.eu/709e371d/syx50js8oj63z98d/zwyciezca.jpg",
        "sentence": "Nie ma przegranych, są sami zwycięzcy.",
        "p1": "существительное, мужской род",
        "p2": "им.п. - zwycięzca / zwycięzcy ",
        "p3": "род.п. — zwycięzcy / zwycięzców",
        "p4": "дат.п. — zwycięzcy / zwycięzcom ",
        "p5": "вин.п. — zwycięzcę / zwycięzcę",
        "p6": "твор.п. — zwycięzcą / zwycięzcami ",
        "p7": "предл.п. — zwycięzcy / zwycięzcach ",
        "p8": "зват.п. — zwycięzco / zwycięzcy",
        "audio": "./audio/04B/zwycięzca.mp3"
    },
};


function showPopup(el) {
  if (!el || !el.dataset || !el.dataset.id) return;
  const id = el.dataset.id;
  const data = wordData[id];
  if (!data) return;

  document.getElementById('popupWord').textContent = data.word;
  document.getElementById('popupTranslation').textContent = data.translation;
 document.getElementById('popupDetails').innerHTML = `
  <span style="color: green;">${data.p1}</span><br>
  ${data.p2}<br>
  ${data.p3}<br>
  ${data.p4}<br>
  ${data.p5}<br>
  ${data.p6}<br>
  ${data.p7}<br>
  ${data.p8}
`;
  document.getElementById('popupSentence').textContent = data.sentence;
  document.getElementById('popupImage').src = data.image;

  const audio = document.getElementById('popupAudio');
  audio.pause();
  audio.src = data.audio;
  audio.currentTime = 0;
  audio.onloadeddata = () => audio.play().catch(e => console.error('Аудио ошибка:', e));

  document.getElementById('popupOverlay').style.display = 'flex';
}

function hidePopup() {
  document.getElementById('popupOverlay').style.display = 'none';
  const audio = document.getElementById('popupAudio');
  if (audio) audio.pause();
}